### ISSUE TITLE
Help with cli commanding for unlocking

### ISSUE THREAD

**Issue by rumourscape** [logicalmechanism/Token-Sale-Plutus-Contract#3]
I am using the following command to unlock the smart contract on testnet.
```
cardano-cli transaction build --alonzo-era --tx-in 4731b521ac304ad97b5f98796585e9970a241e9270f5297419f7699ead6a61af#1 --tx-in a3d24bad406fbf1839bca53576acdae6dbfdffc8035b1e4eb2dca544b8f56bab#0 --tx-in-script-file token_sale.plutus --tx-in-datum-value 42 --tx-in-redeemer-value '""' --tx-in-collateral 504b6034fff4628bbb947945bec1a876105e27f660d32e1af474abbf5bc0f23f#0 --tx-out $(cat pay
ment.addr)+12000000 --change-address $(cat payment.addr) --protocol-params-file protocol.json --out-file unlock.raw --testnet-magic $MAGIC
```
I receive the error, ```the impossible happened: RedeemerNotNeeded ScriptWitnessIndexTxIn 1```

What is the right way to redeem it.

**Comment by logicalmechanism** [comment]
```bash
cardano-cli transaction build \
--alonzo-era \
--tx-in 4731b521ac304ad97b5f98796585e9970a241e9270f5297419f7699ead6a61af#1 \
--tx-in a3d24bad406fbf1839bca53576acdae6dbfdffc8035b1e4eb2dca544b8f56bab#0 \
--tx-in-script-file token_sale.plutus \
--tx-in-datum-value 42 \
--tx-in-redeemer-value '""' \
--tx-in-collateral 504b6034fff4628bbb947945bec1a876105e27f660d32e1af474abbf5bc0f23f#0 \
--tx-out $(cat payment.addr)+12000000 \
--change-address $(cat payment.addr) \
--protocol-params-file protocol.json \
--out-file unlock.raw \
--testnet-magic $MAGIC
```

When spending a UTxO inside a smart contract you need to send in the datum-hash and the datum value along with the redeemer. So that parameter is missing for one. If the UTxO inside the contract does not have a datum hash then it is stuck inside the contract.

Also order matters when using transaction build. The datum value and hash must follow the tx-out parameter.

Use cardano-cli transaction build --help and follow the order inside the help screen for the order of the parameters. Try that out and see what happens.

When I use bash to interact with a smart contract my build call looks something like

```bash
cardano-cli transaction build \
    --alonzo-era \
    --protocol-params-file protocol.json \
    --invalid-hereafter ${FINAL_TIP} \
    --out-file buy-asset.draft \
    --change-address ${BUYER_ADDRESS} \
    --tx-in ${BUYER_TXIN} \
    --tx-in-collateral ${COLLAT_TXIN} \
    --tx-in ${SCRIPT_TXIN} \
    --tx-out ${BUYER_ADDRESS}+${LOVELACE_VALUE}\
    --tx-out-datum-hash ${DATUM_HASH} \
    --tx-in-datum-value ${DATUM_VALUE}\
    --tx-in-redeemer-value ${REDEEMER_VALUE} \
    --tx-in-script-file token_sale.plutus \
    --testnet-magic ${MAGIC_NUMBER}
```

See how my tx-out parameter is immediately followed by the datum hash and value.

**Comment by rumourscape** [comment]
I followed your suggestion but I am now receiving this error.

```
Command failed: transaction build  Error: The following scripts have execution failures:
the script for transaction input 0 (in the order of the TxIds) failed with 
The Plutus script evaluation failed: An error has occurred:  User error:
The provided Plutus code called 'error'.
```

Can you show me what your build command looks like for initially locking the NFT.

**Comment by logicalmechanism** [comment]
Initially locking? Like sending a token into the smart contract?

```
cardano-cli transaction build \
    --alonzo-era \
    --protocol-params-file protocol.json \
    --invalid-hereafter ${FINAL_TIP} \
    --out-file buy-asset.draft \
    --change-address ${BUYER_ADDRESS} \
    --tx-in ${BUYER_TXIN} \
    --tx-out ${SCRIPT_ADDRESS}+${LOVELACE_VALUE}\
    --tx-out-datum-hash ${DATUM_HASH} \
    --testnet-magic ${MAGIC_NUMBER}
```

I would suggest using my ready use python scripts for this. It was meant to be simple and automate the process.

That error you got is a validation error I think which means that something about how you made the contract is not being satisfied. If you are using the token sale contract then you will need to send an additional tx-out to the seller address with the specific cost defined in the parameter section. 

If you were trying to spend a UTxO from a script address and you are using a correctly compiled token sale contract then yeah it would fail with that error. If that is the case then follow this code:

```
cardano-cli transaction build \
    --alonzo-era \
    --protocol-params-file protocol.json \
    --invalid-hereafter ${FINAL_TIP} \
    --out-file buy-asset.draft \
    --change-address ${BUYER_ADDRESS} \
    --tx-in ${BUYER_TXIN} \
    --tx-in-collateral ${COLLAT_TXIN} \
    --tx-in ${SCRIPT_TXIN} \
    --tx-out ${SELLER_ADDRESS}+${TOKEN_COST_VALUE} \ # This is paying the seller the cost of the token.
    --tx-out ${BUYER_ADDRESS}+${LOVELACE_VALUE} \ # This is spending the script utxo into the buyer wallet
    --tx-out-datum-hash ${DATUM_HASH} \
    --tx-in-datum-value ${DATUM_VALUE} \
    --tx-in-redeemer-value ${REDEEMER_VALUE} \
    --tx-in-script-file token_sale.plutus \
    --testnet-magic ${MAGIC_NUMBER}
```
You need to satisfy the on-chain validation to spend a script UTxO. If you are sending a token or Lovelace into the contract then all you need to do is assign a datum hash to it.

**Comment by logicalmechanism** [comment]
I will assume this issue has been resolved. Please open a discussion for further questions.
